# Data Collection Notebook
#
# This notebook collects movie data from the TMDB API and saves it as movies_data.csv.
# The notebook has already been executed. The resulting dataset is included in the repository.
# For analysis, see analysis.ipynb.

In [ ]:
import requests
import pandas as pd
from google.colab import userdata

In [ ]:
# token from colab secrets and url for the TMDB API auth
my_token = userdata.get('TMDBKEY')

In [ ]:
headers = {
    "accept": "application/json",
    "Authorization": f"Bearer {my_token}"
}

In [ ]:
all_movies = []

for page in range(1, 26):   # 25 pages = 500 movies
    movies_url = f"https://api.themoviedb.org/3/movie/popular?page={page}"
    movies_response = requests.get(movies_url, headers=headers)
    movies_data = movies_response.json()

    for movie in movies_data["results"]:
        movie_id = movie["id"]

        detail_url = f"https://api.themoviedb.org/3/movie/{movie_id}"
        detail_response = requests.get(detail_url, headers=headers)
        detail_data = detail_response.json()


        genres_list = [g["name"] for g in detail_data.get("genres", [])]

        genres_string = ", ".join(genres_list)


        release_date = detail_data.get("release_date")

        if release_date:
            year = release_date[:4]
        else:
            year = None



        all_movies.append({
            "movie_id": detail_data.get("id"),
            "title": detail_data.get("title"),
            "release_date": release_date,
            "year": year,
            "genres": genres_string,
            "revenue": detail_data.get("revenue", 0),
            "budget": detail_data.get("budget", 0),
            "runtime": detail_data.get("runtime"),
            "rating": detail_data.get("vote_average")
        })

movies_df = pd.DataFrame(all_movies)

movies_df.to_csv("movies_data.csv", index=False)

print("CSV file saved successfully.")
movies_df.head()

CSV file saved successfully.

,movie_id,title,release_date,year,genres,revenue,budget,runtime,rating
0,1226863,The Super Mario Galaxy Movie,2026-04-01,2026,"Family, Comedy, Adventure, Fantasy, Animation",941200000,110000000,98,6.700
1,1007757,Swapped,2026-05-01,2026,"Adventure, Animation, Family, Fantasy",0,0,102,8.884
2,1318447,Apex,2026-04-24,2026,"Action, Thriller",0,0,96,6.550
3,10867,Malena,2000-10-27,2000,Drama,14493284,0,108,7.431
4,1198994,Send Help,2026-01-22,2026,"Horror, Thriller, Comedy",94041481,40000000,113,7.022

In [ ]:
movies_df.describe()

           movie_id       revenue        budget     runtime      rating
count  5.000000e+02  5.000000e+02  5.000000e+02  500.000000  500.000000
mean   6.298800e+05  2.864918e+08  5.900177e+07  113.526000    6.825728
std    5.558796e+05  4.343475e+08  7.954691e+07   34.934254    1.524712
min    1.200000e+01  0.000000e+00  0.000000e+00    0.000000    0.000000
25%    1.984725e+04  0.000000e+00  0.000000e+00   95.000000    6.387000
50%    5.376030e+05  6.967906e+07  2.000000e+07  110.000000    7.083500
75%    1.173497e+06  4.367291e+08  9.000000e+07  132.000000    7.704250
max    1.688652e+06  2.923706e+09  4.000000e+08  242.000000    9.000000

In [ ]:
print(len(movies_df))

500